### ISSUE TITLE
Doesn't work on raspberry pi os Before update

### ISSUE THREAD

**Issue by MathieuCGit** [osaelectronics/DACBerry-400#3]
Hello,

I just can't install the driver on my raspberry pi 400. I'm using the last iso of raspberry pi OS and I've tried to install before updateing my system. Some ideas ?

Here is the output : 

```
pi@raspberrypi:~/Desktop $ ./dacberry400.sh 

This script will install everything needed to use
DACBerry 400 Series

Always be careful when running scripts and commands copied
from the internet. Ensure they are from a trusted source.

If you want to see what this script does before running it,
you should run: 'curl http://get.osaelectronics.com/dacberry400'

This hardware is not supported, sorry!
Config files have been left untouched

pi@raspberrypi:~/Desktop $ uname -r
5.10.63-v8+

```

**Comment by osaelectronics** [comment]
Hello Mathieu,

I think is because V8+ is not yet supported. Let me take a quick look and I will reply you back.

**Comment by MathieuCGit** [comment]
Hello,

Some news ? If you couldn't provide the *.ko driver, please, at least provide the driver source code, this way everyone can compile it by himself.

regrads

**Comment by osaelectronics** [comment]
Hello Mathieu,

As I said to you via email, the .ko files are here on github. In any case we are compiling for V8+.

Thank you!

**Comment by MathieuCGit** [comment]
Hello,

Ok, so I need it to work so I'm trying to load modules by myself,  may I expect some help ? Here are the outputs I got : 

```
pi@Pianoteq ->sudo insmod /lib/modules/5.10.63-v8+/kernel/sound/soc/bcm/dacberry400.ko
insmod: ERROR: could not insert module /lib/modules/5.10.63-v8+/kernel/sound/soc/bcm/dacberry400.ko: Invalid module format

pi@Pianoteq ->sudo insmod /lib/modules/5.10.63-v8+/kernel/sound/soc/codecs/snd-soc-tlv320aic3x.ko
insmod: ERROR: could not insert module /lib/modules/5.10.63-v8+/kernel/sound/soc/codecs/snd-soc-tlv320aic3x.ko: Invalid module format
```

And got the same with modprobe forcing

```
pi@Pianoteq ->sudo modprobe --force dacberry400
modprobe: ERROR: could not insert 'dacberry400': Exec format error
```

I created dtbo file (by looking into your bash script)

```
pi@Pianoteq ->ls /boot/overlays/dacberry400.dtbo
/boot/overlays/dacberry400.dtbo
```

So it's clearly realated to a wrong kernel version and I can't ompile it by myself as I haven't the sources...so, what am I supposed to do now ?

It would really be easier if you provide the real source code and ever stuff needed to compile our own kernel module (*.c, *.h, make file, etc.)

**Comment by MathieuCGit** [comment]
Well, some progress I guess but your script still doesn't recognize a uname -m returning aarch64, please could you update your script to be really compatible with ARMV8 architecture and install the good drivers ?

**Comment by daeavelwyn** [comment]
just got my and can't use it as it doesn't support aarch64 / armv8 architeture BUT this arch is the raspberry400 basic specification, so you sell hardware and doesn't provide the basics ?? Please, release an aarch64 driver ! Or at least, as mentioned in previous post, make a /src/ repos with source code users can compile by themselves.

**Comment by andypiper** [comment]
I'm running the following (latest Bullseye Raspberry Pi OS on Pi 400)

`Linux pi400 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux`

I'm not able to use the modules supplied and would like to be able to compile something that works. Could you share the source? Maybe switch to a dkms build which could work across multiple kernel versions.

I would also suggest that you update the product pages and repository README to make it very clear that the card only works with 32-bit Pi 400 and very specific kernel vesions, until you resolve this. At the moment, it is not usable. 

(I sent you a message via the contact form on the website)

**Comment by andypiper** [comment]
Have not heard back via the website form. Yesterday, the 64-bit builds came out of beta. Any progress on this issue, please?

**Comment by MathieuCGit** [comment]
Hi Andy,
No progress at all....since months...it sounds like OSA Electronics sells hardware without providing the minimum....

**Comment by daeavelwyn** [comment]
Clearly, I'm working on master keyboard prototypes, and I think i gonna switch to another hardware because of those lack of support.

**Comment by osaelectronics** [comment]
We are giving official support for only Pi OS, for any other custom builds, you need to wait. Please do not blame on the company or on the Hardware, that's not polite from your side. We have more products and we need to take care of all of them. 

If we do not yet release the full source code is because it's not ready at all, we don't want to release something that still has some bug, I think this is understandable. This is also the main reason why the M version is not yet on sale.

If some day Pi org decides to help us with the driver and finally include it on all releases, then this will help to all of us, but so far no luck.

Is not that easy to run a company. Plus lot of shortage those days and too much work to do. So please, be patient, be kind, and avoid blaming. 

Thank you everybody,
Oriol.

**Comment by MathieuCGit** [comment]
Hello Oriol,

You are right, sorry for my bad words, I know you are a small company, but you claimed to support Pi OS, but Pi OS is 64bits since may 2020 ! See here : [https://downloads.raspberrypi.org/raspios_arm64/images/](url) 

If you provided the sources, I'd probably already compile the driver on my side and I even could have made a pull request and share it to the community. This is why I'm quite rude and have been upset. I feel a bit frustrated because I know this is a good board but I can't use it because real-time audio processing needs 64bit use.

**Comment by osaelectronics** [comment]
Hello Mathieu,

Thank you for your comprehension. 

The problem here is that we started the development of the driver focused on arm v7 only, and we had many problems with it. We still need to fix some small issues with the codec power up routine, the default Texas Instrument driver handles it in a wrong way and codec is powered up/down every time just before I2S lines came up and creates a small "pop" noise all the time, on system startup, and when you launch any song/file. I am working closely with driver developer to fix all of this ASAP, but is not that easy. Also working to release 10.92 driver and source for aarch 64. We will provide the source too within the next days so you can also take a look to it/give a try.

The Codec is quite powerful and has a lot tweaks, of it sounds pretty good, this is why we have choose that one for this board, also you can populate external clock for better performance and use the board/codec in master mode, what will give even a much better performance. This is the idea for the DACBerry 400 S+, but we need to fix many things here with the driver before of that.

I can understand the fustration of all of you, but believe me if I say we are doing our bst with this and working as fast as we can.

I will keep all of you updated this week.

Thank you.
Oriol.

**Comment by MathieuCGit** [comment]
Hello,
Late reply because I'm now using another board but I've tried to compile the sources and it works quite well on my side. The only problems are the ones you already mentioned, but as I'm using it for a MIDI controller, it's not a problem (the pop appears only on load the first time).
So I hope you will find a way to get it work fully.

**Comment by osaelectronics** [comment]
Hello,

No worries Mathieu. I am glad you finallly solved the problem. About thee pop, if you find a solution let me know, or just do a push and we will take a look to your code.

Best,
Oriol.
